version: 2
updates:
  - package-ecosystem: npm
    directory: '/website'
    schedule:
      interval: monthly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - tuist/core
    labels:
      - dependencies
      - automerge
  - package-ecosystem: npm
    directory: '/next'
    schedule:
      interval: monthly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - tuist/core
    labels:
      - dependencies
      - automerge
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: monthly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - tuist/core
    labels:
      - dependencies
      - automerge
